common-obj-$(CONFIG_PCI) += nv2a_debug.o
common-obj-$(CONFIG_PCI) += nv2a_psh.o
common-obj-$(CONFIG_PCI) += nv2a_shaders.o
common-obj-$(CONFIG_PCI) += nv2a_vsh.o
common-obj-$(CONFIG_PCI) += g-lru-cache.o
common-obj-$(CONFIG_PCI) += swizzle.o

obj-$(CONFIG_PCI) += nv2a.o
nv2a.o-cflags := -Wno-unused-variable
nv2a.o-cflags += -Wno-unused-but-set-variable
